### ISSUE TITLE
For loop zou je kunnen vervangen door een .map functie? :thinking:

### ISSUE THREAD

**Issue by noyamirai** [Michelwas97/MirandasVerhalen#1]
https://github.com/Michelwas97/MirandasVerhalen/blob/a1bcc1ca35481a9257e24416b9405ba43b702c7d/mirandasverhalen/scripts/main.js#L36-L56

**Comment by Michelwas97** [comment]
Thanks, had nog niet geoefend met .map dit heeft me veel geleerd het is aangepast :)
